import { MageList } from "./mage.model";

export const MAGE_LIST : MageList = [
    {
        id: 1,
        name: 'Asta',
        life: 28,
        damage: 3,
        picture: 'assets/Asta.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 2,
        name: 'Yami',
        life: 35,
        damage: 3,
        picture: 'assets/Yami.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 3,
        name: 'Noelle',
        life: 25,
        damage: 3,
        picture: 'assets/Noelle.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 4,
        name: 'Finral',
        life: 20,
        damage: 3,
        picture: 'assets/Finral.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 5,
        name: 'Luck',
        life: 20,
        damage: 3,
        picture: 'assets/Luck.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 6,
        name: 'Vanessa',
        life: 20,
        damage: 3,
        picture: 'assets/Vanessa.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 7,
        name: 'Zora',
        life: 29,
        damage: 3,
        picture: 'assets/Zora.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 8,
        name: 'Magna',
        life: 29,
        damage: 3,
        picture: 'assets/Magna.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
    {
        id: 9,
        name: 'Charmy',
        life: 10,
        damage: 3,
        picture: 'assets/Charmy.jpg',
        team: ['Taureau Noir'],
        created: new Date,
    },
];